# Generated by Django 3.0.12 on 2021-03-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('name', models.CharField(max_length=40)),
                ('hero', models.CharField(max_length=40)),
                ('herione', models.CharField(max_length=40)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
